schema_version: 1

context:
  version: "2.2.1"

package:
  name: simple-track
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/simple-track/simple_track-${{ version }}.tar.gz
  sha256: f6ddab3dfb8aa090bb04187f3b354f398856b5dd726937559c826b24c4ef5531

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - simpletrack = run_simple_track:run_tracking

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.2.0
    - pytest >=9.0
    - pytest-cov
    - pytest-xdist
    - pyyaml
    - scipy >=1.15.0
    - scikit-image >=0.25.2

tests:
  - python:
      imports:
        - run_simple_track
        - simpletrack
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - simpletrack --help

about:
  summary: Threshold-based object tracking algorithm for 2D data
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/ParaChute-UK/simple-track/

extra:
  recipe-maintainers:
    - A-Gainford
    - thmstein
